// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDawxKL8cL9cIGAICoZblOPlndezJQ-pg',
    appId: '1:40288658115:web:f9c59e8e52005168f43876',
    messagingSenderId: '40288658115',
    projectId: 'semesterproject-99a2b',
    authDomain: 'semesterproject-99a2b.firebaseapp.com',
    storageBucket: 'semesterproject-99a2b.firebasestorage.app',
    measurementId: 'G-4QVM9VVKQZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIVvkH74dnt8pCGLeRy-vCUrHIHzp6GnE',
    appId: '1:40288658115:android:1aa20ee62464b0dcf43876',
    messagingSenderId: '40288658115',
    projectId: 'semesterproject-99a2b',
    storageBucket: 'semesterproject-99a2b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9Ob41mM8AY-zaEOfBc3O0c6oC4Q03dgY',
    appId: '1:40288658115:ios:c32201d2d42dc099f43876',
    messagingSenderId: '40288658115',
    projectId: 'semesterproject-99a2b',
    storageBucket: 'semesterproject-99a2b.firebasestorage.app',
    iosBundleId: 'com.example.bloombasket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9Ob41mM8AY-zaEOfBc3O0c6oC4Q03dgY',
    appId: '1:40288658115:ios:c32201d2d42dc099f43876',
    messagingSenderId: '40288658115',
    projectId: 'semesterproject-99a2b',
    storageBucket: 'semesterproject-99a2b.firebasestorage.app',
    iosBundleId: 'com.example.bloombasket',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDawxKL8cL9cIGAICoZblOPlndezJQ-pg',
    appId: '1:40288658115:web:d7c190a14a8ff1f1f43876',
    messagingSenderId: '40288658115',
    projectId: 'semesterproject-99a2b',
    authDomain: 'semesterproject-99a2b.firebaseapp.com',
    storageBucket: 'semesterproject-99a2b.firebasestorage.app',
    measurementId: 'G-R0Y2SCYJJR',
  );
}
