// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDv9S11LB2vJyrQegymBUhE5Vw1Y6tsDvQ',
    appId: '1:712198995530:web:752ff10b24944125ce30b3',
    messagingSenderId: '712198995530',
    projectId: 'bloombasket-efb4b',
    authDomain: 'bloombasket-efb4b.firebaseapp.com',
    storageBucket: 'bloombasket-efb4b.firebasestorage.app',
    measurementId: 'G-PYYE7FXMHX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA__89WbPmzd6vbheYgU2cXj2ONdQvDAFk',
    appId: '1:712198995530:android:2af54a8e3506f303ce30b3',
    messagingSenderId: '712198995530',
    projectId: 'bloombasket-efb4b',
    storageBucket: 'bloombasket-efb4b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBzC_2YK2Pk7yOMv_HYR1jRdnun74gT_I',
    appId: '1:712198995530:ios:7eeddaca67d5a594ce30b3',
    messagingSenderId: '712198995530',
    projectId: 'bloombasket-efb4b',
    storageBucket: 'bloombasket-efb4b.firebasestorage.app',
    iosBundleId: 'com.example.bloombasket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBzC_2YK2Pk7yOMv_HYR1jRdnun74gT_I',
    appId: '1:712198995530:ios:7eeddaca67d5a594ce30b3',
    messagingSenderId: '712198995530',
    projectId: 'bloombasket-efb4b',
    storageBucket: 'bloombasket-efb4b.firebasestorage.app',
    iosBundleId: 'com.example.bloombasket',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDv9S11LB2vJyrQegymBUhE5Vw1Y6tsDvQ',
    appId: '1:712198995530:web:56fc209a0f5cc7bdce30b3',
    messagingSenderId: '712198995530',
    projectId: 'bloombasket-efb4b',
    authDomain: 'bloombasket-efb4b.firebaseapp.com',
    storageBucket: 'bloombasket-efb4b.firebasestorage.app',
    measurementId: 'G-DV0JRJ2L59',
  );

}